### ISSUE TITLE
Multiple files under `scripts/`

### ISSUE THREAD

**Issue by catboxanon** [Metachs/sdwebui-nai-api#1]
These files should be moved into an external folder next to the `scripts` folder instead, maybe something such as `nai`, to prevent each file being executed on webui startup.

For reference, see:
https://github.com/udon-universe/stable-diffusion-webui-extension-templates/issues/3
https://github.com/vladmandic/automatic/wiki/Extensions#common-mistakes

**Comment by Metachs** [comment]
Thanks, I'll look into it as soon I get a chance, I know the code is a huge mess.  To be honest this project was basically an experiment to see if I could figure out and extend a program written in a language I've never used, without any reference material beyond the program itself. From the looks of the "common mistakes" list, looking at other extensions was a very bad way to learn.
