### ISSUE TITLE
Auto wait if hit with 429?

### ISSUE THREAD

**Issue by Wavuwavu** [Metachs/sdwebui-nai-api#11]
Hi,

If you leave a long batch on after a while you get hit with 
"ERROR: Request 1/1 Failed - Error Code:429 Concurrent free generation requests are not allowed"
And then it seems it keeps hammering it with requests until it works.

In settings, I see "Maximum time to wait before failing when a free opus request is rejected due to one already in progress."
Which I assume is related to this, but it doesn't seem to work? I set it to 120 but I see it keeps retrying every 5–10 seconds anyway. 

Just worried the NAI devs won't like me doing this. Thanks.

**Comment by Metachs** [comment]
That option actually works the other way around, it sets the maximum total time to wait, if you set it to zero, it will disable the wait and retry on 429 errors.

**Comment by Metachs** [comment]
Yeah all that setting does is control the total time, the 5 second wait time was hard coded. I just added an extra setting which lets you control wait time between retries for 429 errors, which should fix that.

**Comment by Metachs** [comment]
Of course, that should be fixed now.

**Comment by Metachs** [comment]
Should work now, actually tested it this time.
