### ISSUE TITLE
NAI weights to A1111 + Convert Prompts for NAI settings and escape parentheses.

### ISSUE THREAD

**Issue by Wavuwavu** [Metachs/sdwebui-nai-api#12]
Hi,

Just reporting an issue I noticed when my saved png info prompts were coming back with different results.
Turns out the NAI metadata saving omits any \ used. Which are used for getting exact booru tags without emphasizing instead. Like `"Character \(Series\)" or ";\)"` And I use these with "Convert Prompts for NAI"

So if you PNG Info > Send to txt2img images that use \ they will be omitted and thus a different image result with "Convert Prompts for NAI" as those () are now being converted I assume.

However if you use "Convert NAI weights to A1111 when importing NAI prompts" and have "Convert Prompts for NAI" set to never it works but this is to get around that I had A1111 to NAI prompt conversion done in the first place...

**Comment by Metachs** [comment]
Sounds like the problem was that the importer wasn't escaping parenthesis in imported prompts, which were then treated as weights. I updated the importer to escape parenthesis in imported NAI prompts, which should fix the problem.
