### ISSUE TITLE
Vibe Transfer feature

### ISSUE THREAD

**Issue by mouceen** [Metachs/sdwebui-nai-api#13]
New feature just dropped that takes an image as input and few sliders for settings, works similarily to IPAdapter.
Is it possible to add the feature in your extension?

Thanks.

**Comment by Metachs** [comment]
Done, works in txt2img and img2img, haven't tested inpainting.

**Comment by mouceen** [comment]
Legend! I've heard on their discord that inpainting doesn't work with it so don't bother yet.
