### ISSUE TITLE
[Feature request] Auto enhance button

### ISSUE THREAD

**Issue by trihardseven** [Metachs/sdwebui-nai-api#14]
Requesting an option to make it so after making an image, automatically request it to be enhanced and possibly upscaled. I know it's basically just an img2img pass, but it's a lot faster to do it in NAI with two clicks than manually doing it with the webui. So I think a quick auto enhance option would be nice, with the same options it has on NAI so upscale, strength and noise. As well as an option to save or discard pre enhance image. Thank you for the extension.

**Comment by Metachs** [comment]
Unfortunately, this would be tricky with Gradio's architecture, and I haven't been able to think of a way to do it that wouldn't require an excessive amount of additional framework.
