### ISSUE TITLE
404 Network error

### ISSUE THREAD

**Issue by mouceen** [Metachs/sdwebui-nai-api#15]
Haven't used webui for NAI about 7 days. Now I'm getting network error 404 on every generation instantly, and I'm unable to generate any images using the extension. Tested it on the official novelAI website, and everything works there. I have tried resetting API key and it didn't help. They had a recent update to introduce multiple vibe transfer images as input, but I didn't use automatic1111 or the extension for 7 days, so I can't say when exactly it broke for me.

Happy to provide any more information.

**Comment by Metachs** [comment]
Have you updated/pulled the most recent changes? NAI added a new endpoint for image gen last month and the extension was updated to use it shortly afterwards. Since the old endpoint just went offline in the last couple of days, I'd guess you are using an outdated script that is still accessing it.

**Comment by mouceen** [comment]
You're right, that was the issue. Thanks.
