### ISSUE TITLE
[Feature Request] Add a configurable delay between multiple image gens.

### ISSUE THREAD

**Issue by HumbleStranger** [Metachs/sdwebui-nai-api#17]
Just thought that it would be nice to have to be able to have a configurable delay between each generation.
The way it would work is basically:
1. Set the multiple batch gen. Let's say 20.
2. Configure a delay between each batch(let's say, 7 seconds and, preferably, with a random modifier of +- 2 seconds with decimals)
3. Launch the process and go do your thing IRL.

It's perfect for people who have time to spare, but don't want to spend it clicking for single gens all the time to find that one they want or doing multiple single batches that go on continuously without delay and risking getting their account banned.

**Comment by Metachs** [comment]
Added 2 settings to allow this, a base delay and an additional random delay.
