### ISSUE TITLE
[Suggestion] Automatically add 'nsfw' to the beginning of the negative prompt if no such tag is present in the positive prompt

### ISSUE THREAD

**Issue by Deens599** [Metachs/sdwebui-nai-api#29]
The title is pretty self-explanatory. It's something that the NAI website does in the background, so it makes sense to replicate that behavior in the extension for parity's sake.

As a starting point, the line `if 'nsfw' not in prompt: neg = f'nsfw, {neg}'` could be added to the nai_api.py file after line #488 `if tags and tags not in neg: neg = f'{tags}, {neg}'`, though I think it would be best to make it a global setting (on by default).

**Comment by Metachs** [comment]
Probably not going to do this, with all the prompt manipulations that can take place along with importing/reimporting metadata, this is surprisingly complicated (Just stripping invalid characters has caused significant replicability issues), and personally I dislike the idea of altering prompts behind the scenes unless absolutely required.
