### ISSUE TITLE
[Bug] Missing parameters

### ISSUE THREAD

**Issue by Deens599** [Metachs/sdwebui-nai-api#30]
Two new parameters seem to have been added to the API, neither of which is accounted for in the extension, leading to severe mismatches in images generated by the extension and the NAI website when using the Euler Ancestral sampler.

The parameters in question are `"deliberate_euler_ancestral_bug"` and `"prefer_brownian"`, both booleans. It appears that the extension always sends `"deliberate_euler_ancestral_bug": true, "prefer_brownian": false` (presumably the default) to the API, whereas the website uses `"deliberate_euler_ancestral_bug": false, "prefer_brownian": true` with Euler Ancestral specifically.

Below is a pair of example images with exactly the same settings, the first was generated through the extension, the second on the NAI website.

Extension:
![39209-1561154749-1girl, pyra _(xenoblade_), 2b _(nier_automata_) _(cosplay_), artist_kobuichi, artist_muririn, large breasts, red hair, short hai](https://github.com/user-attachments/assets/209df5a8-3895-43b6-a56a-a90ac3ea2ebc)

NAI website:
![5ef871eb-0b8b-4f39-aa08-29a7234a9c87](https://github.com/user-attachments/assets/f8e0770d-285e-4085-af6c-8e3eeac73289)

Non-Ancestral Euler, as well as all other samplers, seem to be unaffected as the website uses the same set of parameters for these samplers as the extension (`"deliberate_euler_ancestral_bug": true, "prefer_brownian": false`).

Extension:
![39210-1561154749-1girl, pyra _(xenoblade_), 2b _(nier_automata_) _(cosplay_), artist_kobuichi, artist_muririn, large breasts, red hair, short hai](https://github.com/user-attachments/assets/b20ae923-9675-4381-a774-c6cb03036db7)

NAI website:
![a63bc4f8-eda3-4ccb-af59-08968c7c9066](https://github.com/user-attachments/assets/14d9057a-c1ba-4ad6-bff4-fb763e072f94)

Overall, the parameters used by the NAI website for each of the samplers are as follows:

Euler: `"deliberate_euler_ancestral_bug": true, "prefer_brownian": false`
Euler Ancestral: `"deliberate_euler_ancestral_bug": false, "prefer_brownian": true`
DPM++ 2S Ancestral: `"deliberate_euler_ancestral_bug": true, "prefer_brownian": false`
DPM++ 2M SDE: `"deliberate_euler_ancestral_bug": true, "prefer_brownian": false`
DPM++ 2M: `"deliberate_euler_ancestral_bug": true, "prefer_brownian": false`
DPM++ SDE: `"deliberate_euler_ancestral_bug": true, "prefer_brownian": false`
DDIM: `"deliberate_euler_ancestral_bug": true, "prefer_brownian": false`

**Comment by Metachs** [comment]
Thanks for catching that, the site only sends those parameters with euler_a and non-native schedulers so it's easy to miss. The default values for those parameters should be set correctly now, and results with euler_a now match the site.
