### ISSUE TITLE
No retry on "Invalid NAI Key" error?

### ISSUE THREAD

**Issue by Wavuwavu** [Metachs/sdwebui-nai-api#7]
Hi again, any chance it could be possible to auto-retry whenever hit with an "Invalid NAI Key" error, like when you get other error messages (such as numbered ones like error 500, etc) instead of interrupting whatever you were trying to do completely?

To elaborate it says invalid NAI key however just retrying manually without changing my key works...

**Comment by Metachs** [comment]
Easy enough, also disabled a redundant account status check before gen.
