### ISSUE TITLE
Toggle/Setting for the conversion of NAI prompts

### ISSUE THREAD

**Issue by Jikko2022** [Metachs/sdwebui-nai-api#8]
Hi would it be possible to enable/disable the conversion of the prompt syntax from NAI to local and vice versa via a setting? I found out that if I import an image the conversion is not working exactly how it should and i get a different result based on the same seed. Using the prompt from the metadata with the "{}" brackets works as intended but the conversion to a numerical value sadly breaks the seed.

Thank you for your time.

**Comment by Metachs** [comment]
Done, should have been there before but apparently I didn't commit that change. However the conversion should be identical, if you have a prompt that doesn't convert one to one, post it so I can look into what is going wrong. (The plain text of the prompt shouldn't matter, just weights, special characters and white space, so you can dummy anything out you don't feel like posting)

**Comment by Metachs** [comment]
I believe I found and resolved the issue (loose non-weight parenthesis were dropped when importing into NAI if the the prompt had A1111 weights). If you get a chance, check and see if the conversion is still breaking prompts, and let me know if it is still broken.
